name: api_call_exercise
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: modules/core
  anime:
    path: modules/anime

  cupertino_icons: ^1.0.5
  get_it: ^7.2.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mockito: ^5.3.0
  bloc_test: ^9.1.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg