// Mocks generated by Mockito 5.3.0 from annotations
// in anime/test/domain/usecases/get_anime_by_genre_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:anime/domain/entities/anime_entity.dart' as _i6;
import 'package:anime/domain/repositories/anime_repository.dart' as _i3;
import 'package:core/failures/failures.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [AnimeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnimeRepository extends _i1.Mock implements _i3.AnimeRepository {
  MockAnimeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.AnimeEntity>>>
      getAnimeTopList() => (super.noSuchMethod(
          Invocation.method(#getAnimeTopList, []),
          returnValue:
              _i4.Future<_i2.Either<_i5.Failure, List<_i6.AnimeEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.AnimeEntity>>(
                      this, Invocation.method(#getAnimeTopList, [])))) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.AnimeEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.AnimeEntity>>> getAnimeByGenre(
          int? genreId) =>
      (super.noSuchMethod(Invocation.method(#getAnimeByGenre, [genreId]),
          returnValue:
              _i4.Future<_i2.Either<_i5.Failure, List<_i6.AnimeEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.AnimeEntity>>(this,
                      Invocation.method(#getAnimeByGenre, [genreId])))) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.AnimeEntity>>>);
}
